BedAndBreakfastGroup16/Controllers/SNSController.cs
using Microsoft.AspNetCore.Mvc;
using Amazon;
using Amazon.SimpleNotificationService;
using Amazon.SimpleNotificationService.Model;
using Microsoft.Extensions.Configuration;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace BedAndBreakfastGroup16.Controllers
{
    public class SNSController : Controller
    {
        private const string topicARN = "arn:aws:sns:us-east-1:107291066015:SNSsample";

        //function 1: to get all the keys back from the appsetting.json
        private List<string> getKeys()
        {
            List<string> keys = new List<string>();

            //1. collect the keys from appsetting.json; link to appsettings.json and get back the values
            var builder = new ConfigurationBuilder()
                            .SetBasePath(Directory.GetCurrentDirectory())
                            .AddJsonFile("appsettings.json");
            IConfigurationRoot conf = builder.Build(); //build the json file

            //2. read the info from json using configure instance
            keys.Add(conf["Keys:Key1"]);
            keys.Add(conf["Keys:Key2"]);
            keys.Add(conf["Keys:Key3"]);

            return keys;
        }



        //function 3: use to subscribe the topics 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> regSubscription(string emailsubscribe)
        {
            List<string> keys = getKeys();
            AmazonSimpleNotificationServiceClient agent = new AmazonSimpleNotificationServiceClient(keys[0], keys[1], keys[2], RegionEndpoint.USEast1);

            try
            {
                SubscribeRequest request = new SubscribeRequest
                {
                    TopicArn = topicARN,
                    Protocol = "email",
                    Endpoint = emailsubscribe
                };
                SubscribeResponse response = await agent.SubscribeAsync(request);
                ViewBag.recordid = response.ResponseMetadata.RequestId;
            }
            catch (AmazonSimpleNotificationServiceException ex)
            {
                return BadRequest(ex.Message);
            }
            return View();
        }
        [Authorize(Roles = "Admin")]
        //function 4: admin broadcast personal message sample
        public IActionResult BroadcastMessagePage()
        {
            return View();
        }

        //function 5: Broadcast Message Action through SNS
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> broadcastmsg(string subject, string msgbody)
        {
            List<string> keys = getKeys();
            AmazonSimpleNotificationServiceClient agent = new AmazonSimpleNotificationServiceClient(keys[0], keys[1], keys[2], RegionEndpoint.USEast1);
            try
            {
                PublishRequest request = new PublishRequest
                {
                    TopicArn = topicARN,
                    Subject = subject,
                    Message = msgbody
                };
                await agent.PublishAsync(request);
            }
            catch (AmazonSimpleNotificationServiceException ex)
            {
                return BadRequest(ex.Message);
            }
            return RedirectToAction("SuccessfulBroadcast");
        }

        public IActionResult SuccessfulBroadcast()
        {
            return View();
        }
    }
}

BedAndBreakfastGroup16/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>VI Boutique Hotel</title>
    <title>@ViewData["Title"] - BedAndBreakfastGroup16</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cabin:400,500,600,700&display=swap" rel="stylesheet">

    <!-- Css Styles from template -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="~/css/flaticon.css" type="text/css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="~/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/magnific-popup.css" type="text/css">
    <link rel="stylesheet" href="~/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/style.css" type="text/css">

    <!-- Styles from project -->
@*    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
 @*   <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="~/BedAndBreakfastGroup16.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="header-section">
        <div class="top-nav">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <ul class="tn-left">
                            <li><i class="fa fa-phone"></i> (12) 345 67890</li>
                            <li><i class="fa fa-envelope"></i> vi.boutique@gmail.com</li>
                        </ul>
                    </div>
                    <div class="col-lg-6">
                        <div class="tn-right">
                            <partial name="_LoginPartial" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="menu-item">
            <div class="container">
                <div class="row">
                    <div class="col-lg-2">
                        <div class="logo">
                            <a asp-area="" asp-controller="Home" asp-action="Index">
                                <img src="~/img/logo.png" alt="Logo">
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-10">
                        <div class="nav-menu">
                            <nav class="mainmenu">
                                <ul>
                                    <li class="active"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <li><a asp-area="" asp-controller="SNS" asp-action="BroadcastMessagePage">Broadcast Message</a></li>
                                        <li><a asp-area="" asp-controller="Booking" asp-action="viewMessages">Booking Requests</a></li>
                                    } 
                                    <li><a asp-area="" asp-controller="Rooms" asp-action="Index">Rooms</a></li>
                                    <li><a asp-area="" asp-controller="Home" asp-action="AboutUs">About Us</a></li>
                                    <li><a asp-area="" asp-controller="Blogs" asp-action="Index">Blogs</a></li>
                                   
                                    @*<li><a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></li>*@
                                </ul>
                            </nav>
                            <div class="nav-right search-switch">
                                <i class="icon_search"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
@*    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BedAndBreakfastGroup16</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>*@
    <main role="main" class="pb-3">
        @RenderBody()
    </main>


    <!-- Footer Section Begin -->
    <footer class="footer-section">
        <div class="container">
            <div class="footer-text">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="ft-about">
                            <div class="logo">
                                <a href="#">
                                    <img src="~/img/footerlogo.png" alt="Logo">
                                    
                                </a>
                            </div>
                            <p>We inspire and reach millions of travelers<br /> across 90 local websites</p>
                            <div class="fa-social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-tripadvisor"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                                <a href="#"><i class="fa fa-youtube-play"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 offset-lg-1">
                        <div class="ft-contact">
                            <h6>Contact Us</h6>
                            <ul>
                                <li>(12) 345 67890</li>
                                <li>vi.boutique@mail.com</li>
                                <li>Pasir Penambang, 45000 Kuala Selangor, Selangor</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3 offset-lg-1">
                        <div class="ft-newslatter">
                            <h6>New latest</h6>
                            <p>Get the latest updates and offers.</p>
                            <form method="post" asp-action="regSubscription" asp-controller="SNS" class="fn-form">
                                <input type="email" name="emailsubscribe" placeholder="aaa@gmail.com"/>
                            <button type="submit"><i class="fa fa-send"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright-option">
            <div class="container">
                <div class="row">
                    <div class="col-lg-5">
                        <div class="co-text">
                            <p>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | DDAC GROUP 16
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->


    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/jquery-ui.min.js"></script>
    <script src="~/js/jquery.slicknav.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/main.js"></script>

    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
@*    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    @*<script src="~/js/site.js" asp-append-version="true"></script>*@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>